# Generated by Django 2.0 on 2017-12-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=200)),
                ('message_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('session_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('expire_date', models.DateTimeField(verbose_name='date expired')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='session_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.UserSession'),
        ),
    ]
