# Generated by Django 2.0 on 2017-12-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_usermessage_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='opponent',
            new_name='opponent_id',
        ),
    ]
